monitor.alsa.rules = [
  {
    matches = [
      { node.name = "~alsa_output.*" },
      { node.name = "~alsa_input.*" }
    ]
    actions = {
      update-props = {
        session.suspend-timeout-seconds = 0
        node.pause-on-idle = false
        api.alsa.headroom = 8192
        api.alsa.period-size = 1024
        api.alsa.disable-batch = false
        resample.quality = 4
      }
    }
  }
]
