# 3-finger vertical: volume control smooth 5% via 1% x5 delayed 100ms
gesture swipe up    3 /home/michi/.config/libinput-gestures/volume-up.sh
gesture swipe down  3 /home/michi/.config/libinput-gestures/volume-down.sh
